In [13]:
import matplotlib.pyplot as plt
from tqdm import tqdm # For progress bar.
import numpy as np # To do array operations.
import os # To iterate through directories and join paths.
import cv2 # To do image operations.
import pickle
import random

# Loading the dataset:

In [14]:
from fpCSC592.data_utils import create_training_data
from fpCSC592.data_utils import convert

In [5]:
# ####################################################
# NOTE: Cange this path if using on other computers. #
# ################################################## #

DATADIR = "/Users/shehjarsadhu/Desktop/Spring19/CSC592DeepLearning/MalariaProject/cell_images"
CATEGORIES = ["Uninfected", "Parasitized"]

train  = create_training_data(DATADIR,CATEGORIES)

100%|██████████| 13780/13780 [00:12<00:00, 1085.25it/s]


In [6]:
X , y = convert(train)

[[[[  0]
   [  0]
   [  0]
   ...
   [  0]
   [  0]
   [  0]]

  [[  0]
   [  0]
   [  0]
   ...
   [  0]
   [  0]
   [  0]]

  [[  0]
   [  0]
   [  0]
   ...
   [  0]
   [  0]
   [  0]]

  ...

  [[  0]
   [  0]
   [  0]
   ...
   [139]
   [ 89]
   [175]]

  [[141]
   [ 91]
   [177]
   ...
   [143]
   [ 93]
   [179]]

  [[142]
   [ 92]
   [178]
   ...
   [  0]
   [  0]
   [  0]]]


 [[[  0]
   [  0]
   [  0]
   ...
   [144]
   [ 92]
   [178]]

  [[133]
   [ 79]
   [169]
   ...
   [144]
   [ 94]
   [178]]

  [[143]
   [ 92]
   [179]
   ...
   [  0]
   [  0]
   [  0]]

  ...

  [[  0]
   [  0]
   [  0]
   ...
   [144]
   [ 93]
   [180]]

  [[142]
   [ 91]
   [178]
   ...
   [146]
   [ 95]
   [182]]

  [[143]
   [ 93]
   [177]
   ...
   [  0]
   [  0]
   [  0]]]


 [[[165]
   [150]
   [216]
   ...
   [144]
   [ 93]
   [180]]

  [[146]
   [ 94]
   [181]
   ...
   [143]
   [ 92]
   [179]]

  [[145]
   [ 95]
   [179]
   ...
   [  0]
   [  0]
   [  0]]

  ...

  [[  0]
   [  0]
   [  0]
   

In [7]:
# To save the data so we don't have to load it over and over again.
pickle_out = open("X.pickle","wb")
pickle.dump(X, pickle_out)
pickle_out.close()
pickle_out = open("y.pickle","wb")
pickle.dump(y, pickle_out)
pickle_out.close()

In [8]:
pickle_in = open("X.pickle","rb")
X = pickle.load(pickle_in)
pickle_in = open("y.pickle","rb")
y = pickle.load(pickle_in)

In [9]:
## Preprocessing:
X = X/255.0
print(X)

[[[0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]
  ...
  [0.         0.         0.         ... 0.54509804 0.34901961 0.68627451]
  [0.55294118 0.35686275 0.69411765 ... 0.56078431 0.36470588 0.70196078]
  [0.55686275 0.36078431 0.69803922 ... 0.         0.         0.        ]]

 [[0.         0.         0.         ... 0.56470588 0.36078431 0.69803922]
  [0.52156863 0.30980392 0.6627451  ... 0.56470588 0.36862745 0.69803922]
  [0.56078431 0.36078431 0.70196078 ... 0.         0.         0.        ]
  ...
  [0.         0.         0.         ... 0.56470588 0.36470588 0.70588235]
  [0.55686275 0.35686275 0.69803922 ... 0.57254902 0.37254902 0.71372549]
  [0.56078431 0.36470588 0.69411765 ... 0.         0.         0.        ]]

 [[0.64705882 0.58823529 0.84705882 ... 0.56470588 0.36470588 0.70588235]
  [0.57254902 0.368627

# Tensor Flow:

In [10]:
import tensorflow as tf
tf.VERSION

'1.13.1'

In [11]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv3D, MaxPooling3D

## Convolutional neural network

In [12]:
tf.enable_eager_execution()