## Getting started :

In [7]:
import torch 

In [8]:
print(torch.__version__)

1.0.1.post2


In [9]:
torch.cuda.is_available() #I don't have a GUP....::((

False

## Using CUDA :

In [10]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [ ]:
r = t.cuda() #THIS SUCKS I WANT A GPU!!

## THE  Data Structures : Tensors 

In [15]:
# In eucledian space [1,2,3] is 3 dimentional. has 3 components 
# In tensor space [1,2,3]  is 1 dimention and..
#   [1,2,3],
#   [4,5,6],
#   [7,8,9] --- This is 3 Dimention has 9 components.
#
#
new_tensor = torch.tensor(([1,2,3],
                 [4,5,6],
                 [7,8,9]))


In [18]:
new_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Rank, Axes, and Shape

#### Rank

In [22]:
a = [1,2,3] # Rank 1 tensor.
            # ==>
a[2]        # 1 indicie.

3

In [37]:
dd = [[1,2,3],      # Rank 2 Tensor.
     [4,5,6],
    [7,8,9]]        # ==> We have a matrix, We have a 2D array, We have a 2d tensor.
dd[0][1]            # We need 2 indicies to access one element. 

2

In [27]:
#Rank: Number of dimentions in a tensor.
# ---How many indicies are required to access specfic data element contained within a tensor. like a[2] = 3!

#### Axes

In [30]:
# Axes of a tensor is a specfic dimention.
# Rank 2 Tensor ==> the tensor has 2 dimentions 
#  ==>
# Tensor has 2 Axis.

In [5]:
t = [1,2,3]  # Length of this axis is 3 so we can only access up to index 2. 
print(t[0])
print(t[1])
print(t[2])

1
2
3


In [13]:
# ------------------Axis of length 4.-----------
# print(1st axis => t[0] 2nd axis => [0])
# print(t[1][0])
# print(t[2][0])

# print(t[0][1])
# print(t[1][1])
# print(t[2][1])
#
# print(t[0][2])
# print(t[1][2])
# print(t[2][2])

# print(t[0][3])
# print(t[1][3])
# print(t[2][3])
#----------------------------------------------

### Shape

In [21]:
#now dd is a torch tensor.
dd_t = torch.tensor(dd)
dd_t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
type(dd_t)

torch.Tensor

In [23]:
dd_t.shape

torch.Size([3, 3])

In [34]:
# rank of a tensor == the length of it's shape.
rank_dd_t  = len(dd_t.shape)
print("rank = length(shape) = ",rank_dd_t)

rank = length(shape) =  2


In [35]:
dd_t.shape

torch.Size([3, 3])

#### Reshape

In [36]:
print(dd_t.reshape(1,9))
print(dd_t.reshape(1,9).shape)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 9])


#  Convolutional Neural Networks and Feature Maps :